"""add review model and update user book loan models

Revision ID: 651bfa0dc93e
Revises: 75b418a5f848
Create Date: 2025-12-05 03:03:21.963090

"""
from typing import Sequence, Union

import advanced_alchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '651bfa0dc93e'
down_revision: Union[str, Sequence[str], None] = '75b418a5f848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None: #ayudado con ia
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Crear el tipo ENUM para LoanStatus
    loanstatus_enum = sa.Enum('ACTIVE', 'RETURNED', 'OVERDUE', name='loanstatus')
    loanstatus_enum.create(op.get_bind(), checkfirst=True)
    
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('book_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_reviews_book_id_books')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    
    # Agregar columnas a books con valores por defecto temporales
    op.add_column('books', sa.Column('stock', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('books', sa.Column('description', sa.String(), nullable=True))
    op.add_column('books', sa.Column('language', sa.String(), nullable=False, server_default='es'))
    op.add_column('books', sa.Column('publisher', sa.String(), nullable=True))
    
    # Remover server_default después de agregar las columnas
    op.alter_column('books', 'stock', server_default=None)
    op.alter_column('books', 'language', server_default=None)
    
    # Agregar columnas a loans con valores por defecto temporales
    op.add_column('loans', sa.Column('due_date', sa.Date(), nullable=False, server_default=sa.func.current_date()))
    op.add_column('loans', sa.Column('fine_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('loans', sa.Column('status', sa.Enum('ACTIVE', 'RETURNED', 'OVERDUE', name='loanstatus'), nullable=False, server_default='ACTIVE'))
    
    # Remover server_default después de agregar las columnas
    op.alter_column('loans', 'due_date', server_default=None)
    op.alter_column('loans', 'status', server_default=None)
    
    # Agregar columnas a users como nullable primero
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    
    # Actualizar usuarios existentes con emails temporales únicos
    op.execute("UPDATE users SET email = username || '@example.com' WHERE email IS NULL")
    
    # Ahora hacer email NOT NULL
    op.alter_column('users', 'email', nullable=False)
    op.alter_column('users', 'is_active', server_default=None)
    
    # Crear constraint unique para email
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None: #ayudado con ia
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'email')
    op.drop_column('loans', 'status')
    op.drop_column('loans', 'fine_amount')
    op.drop_column('loans', 'due_date')
    op.drop_column('books', 'publisher')
    op.drop_column('books', 'language')
    op.drop_column('books', 'description')
    op.drop_column('books', 'stock')
    op.drop_table('reviews')
    
    # Eliminar el tipo ENUM
    sa.Enum(name='loanstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###